### ISSUE TITLE
Nrtsearch restarts during backup creates garbage files and unneeded snapshots which are never cleaned up

### ISSUE THREAD

**Issue by sarthakn7** [Yelp/nrtsearch#208]
If nrtsearch restarts while a backup is in progress, the temporary file created for backup as well as index snapshot are not cleaned up. In case of an error during backup we remove the temporary file but don't release the snapshot. This can lead to ballooning disk usage eventually making the disk full.

Proposed steps to handle this:
- Before starting backup: commit and write the current index gen to a file that would indicate that a backup is starting, let's call this backup indicator file
- If backup completes successfully - delete the backup indicator file after cleaning up temporary files and releasing snapshot
- If a backup throws an error: release created snapshot along with cleaning up temporary files and then delete the backup indicator file
- When nrtsearch starts up: if a backup indicator file is found, get all snapshots and release snapshots having index gen newer than the one in backup indicator file and delete any temporary files. Then delete the backup indicator file

Additionally we can avoid multiple backups at the same time by checking for the presence of a backup indicator file before starting a backup.

**Comment by sarthakn7** [comment]
This would also handle cases where an exception like the one below is thrown resulting in the snapshot not being released:
```
java.io.IOException: This archive contains unclosed entries.
        at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:289)
        at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:307)
        at com.yelp.nrtsearch.server.utils.TarImpl.buildTar(TarImpl.java:105)
        at com.yelp.nrtsearch.server.utils.ArchiverImpl.upload(ArchiverImpl.java:183)
        at com.yelp.nrtsearch.server.luceneserver.BackupIndexRequestHandler.uploadArtifacts(BackupIndexRequestHandler.java:93)
        at com.yelp.nrtsearch.server.luceneserver.BackupIndexRequestHandler.handle(BackupIndexRequestHandler.java:59)
        at com.yelp.nrtsearch.server.grpc.LuceneServer$LuceneServerImpl.backupIndex(LuceneServer.java:1182)
        at com.yelp.nrtsearch.server.grpc.LuceneServerGrpc$MethodHandlers.invoke(LuceneServerGrpc.java:2720)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:820)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```
